apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
    inputs:
      a:
        type: string
        default: aaaaaaa
        description: aaa
      n:
        type: number
        default: 1111111
        required: true
        description: "1111"
      cccc:
        type: boolean
        default: true
        required: true
        description: ccc
      dddd:
        type: choice
        options:
          - opt1
          - opt2
        default: opt2
        required: true
        description: ddddd
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
