apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Test multiple environment-based manual approval jobs
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  job1:
    environment: max_env_manual_approval
    steps:
      - name: Some step
        uses: docker://alpine:3.21
        run: |
          echo hello
  job2:
    environment: max_env_manual_approval
    steps:
      - name: Some step
        uses: docker://alpine:3.21
        run: |
          echo hello
